src/Entity/Utilisateur.php
<?php

namespace App\Entity;

use App\Repository\UtilisateurRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity(repositoryClass=UtilisateurRepository::class)
 * @ORM\Table(name="`utilisateur`")
 * @ORM\InheritanceType("JOINED")
 * @ORM\DiscriminatorColumn(name="typeutilisateur", type="string")
 * @ORM\DiscriminatorMap({"Etud"="Etudiant", "Prof"="Professeur"})
 */

class Utilisateur  implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * 
     */
    private $nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $prenom;

     /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private $email;

    
    /**
     * @ORM\Column(type="json")
     */
    private $roles = [];
    
    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     * 
     */
    private $password;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->prenom = $prenom;

        return $this;
    }
    public function getEmail(): ?string
    {
        return $this->email;
    }
    
    public function setEmail(string $email): self
    {
        $this->email = $email;
        
        return $this;
    }
    /*
    public function getMail(): ?string
    {
        return $this->mail;
    }

    public function setMail(string $mail): self
    {
        $this->mail = $mail;

        return $this;
    }

    public function getMdp(): ?string
    {
        return $this->mdp;
    }

    public function setMdp(string $mdp): self
    {
        $this->mdp = $mdp;

        return $this;
    }
    */
    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }
    
    /**
     * @deprecated since Symfony 5.3, use getUserIdentifier instead
     */
    public function getUsername(): string
    {
        return (string) $this->email;
    }
    
    /**
     * @see UserInterface
     */
    public function getRoles(): array
    {
        $roles = $this->roles;
        // guarantee every user at least has ROLE_USER
        $roles[] = 'ROLE_USER';
        
        return array_unique($roles);
    }
    
    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
        
        return $this;
    }
    
    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): string
    {
        return $this->password;
    }
    
    public function setPassword(string $password): self
    {
        $this->password = $password;
        
        return $this;
    }
    
    /**
     * Returning a salt is only needed, if you are not using a modern
     * hashing algorithm (e.g. bcrypt or sodium) in your security.yaml.
     *
     * @see UserInterface
     */
    public function getSalt(): ?string
    {
        return null;
    }
    
    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }
    
    public function serialize() {
        return serialize($this->id);
    }
    
    public function unserialize($data) {
        $this->id = unserialize($data);
    }
}

templates/security/login.html.twig
{% block title %}{% endblock %}

{% block body %}
<head>
    <link rel="stylesheet" type="text/css" href="{{ asset('css_templates/css_login.css') }}" />
     {% block stylesheets %}{% endblock %}
</head>
	
<div class="div_log">

	<form method="post">
		{% if error %}
			<div class="alert alert-danger">{{ error.messageKey|trans(error.messageData, 'security') }}</div>
		{% endif %}

		{% if app.user %}
			<div class="mb-3">
				You are logged in as {{ app.user.username }}, <a href="{{ path('app_logout') }}">Logout</a>
			</div>
		{% endif %}

		<h1 class="h3 mb-3 font-weight-normal">Connexion</h1>
		<label class="titreID" for="inputEmail">Email :</label>
		</br>
		<input type="email" value="{{ last_username }}" name="email" id="inputEmail" class="barre" autocomplete="email" required autofocus>
		</br>
		<label class="titreID" for="inputPassword">Mot de passe :</label>
		</br>
		<input type="password" name="password" id="inputPassword" class="barre" autocomplete="current-password" required>

		<input type="hidden" name="_csrf_token"
			   value="{{ csrf_token('authenticate') }}"
		>
		</br>
    	<a class= "mdpoublier" href="">Mot de passe oublier</a> 

		{#
			Uncomment this section and add a remember_me option below your firewall to activate remember me functionality.
			See https://symfony.com/doc/current/security/remember_me.html

			<div class="checkbox mb-3">
				<label>
					<input type="checkbox" name="_remember_me"> Remember me
				</label>
			</div>
		#}
		</br>
		<button  type="submit" class="tagrandmerelapute">CONNEXION</button>
		
	</form>
</div>
{% endblock %}