src/Entity/Production.php
<?php

namespace App\Entity;

use App\Repository\ProductionRepository;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProductionRepository::class)
 */
class Production
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $designation;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $uri;

    /**
     * @ORM\Column(type="string", length=200)
     */
    private $uri_entier;
    
    /**
    * @ORM\ManyToOne(targetEntity=Situation::class, inversedBy="productions")
    * @ORM\JoinColumn(nullable=false)
    */
    private $situation;

    /**
     * Production constructor.
     * @param $id
     * @param $designation
     * @param $uri
     * @param $uri_entier
     * @param $situation
     */
    public function __construct($id = null, $designation = null, $uri = null, $uri_entier = null, $situation = null)
    {
        $this->id = $id;
        $this->designation = $designation;
        $this->uri = $uri;
        $this->uri_entier = $uri_entier;
        $this->situation = $situation;
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDesignation(): ?string
    {
        return $this->designation;
    }

    public function setDesignation(string $designation): self
    {
        $this->designation = $designation;

        return $this;
    }

    public function getUri(): ?string
    {
        return $this->uri;
    }

    public function setUri(string $uri): self
    {
        $this->uri = $uri;

        return $this;
    }
    
    public function getSituation(): ?Situation
    {
        return $this->situation;
    }
    
    public function setSituation(?Situation $situation): self
    {
        $this->situation = $situation;
        
        return $this;
    }

    /**
     * @return mixed
     */
    public function getUriEntier()
    {
        return $this->uri_entier;
    }

    /**
     * @param mixed $uri_entier
     */
    public function setUriEntier($uri_entier): void
    {
        $this->uri_entier = $uri_entier;
    }

}

src/Form/ProductionType.php
<?php

namespace App\Form;

use App\Entity\Production;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProductionType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('designation')
            ->add('uri', FileType::class, ['label' => 'Uri', 'mapped' => false, 'required' => false])
            ->add('enregistrer', SubmitType::class, ['label' => 'Enregistrer'])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Production::class,
        ]);
    }
}

src/Controller/ProductionController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use App\Entity\Etudiant;
use App\Entity\Production;
use App\Entity\Situation;
use App\Form\SituationType;
use Symfony\Component\Routing\Annotation\Route;
use App\Repository\EtudiantRepository;
use App\Form\ListeSituationType;
use App\Entity\Reformulation;
use App\Form\ProductionType;
use App\Form\ReformulationsType;
use Symfony\Component\Serializer\Encoder\XmlEncoder;
use Symfony\Component\HttpFoundation\File\File;
use Symfony\Component\HttpFoundation\File\UploadedFile;
use App\Service\FileUploader;
use Spipu\Html2Pdf\Html2Pdf;
use Spipu\Html2Pdf\Exception\Html2PdfException;

class ProductionController extends AbstractController
{
    
    /**
     * @Route("/production/ajoutproduction/{id}", name="ajoutproduction")
     */
    public function ajoutproduction(Request $req,int $id, FileUploader $file_uploader): Response
    {
        $user = $this->getUser();
        serialize($user);
        $doctrine = $this->getDoctrine();
        $manager = $doctrine->getManager();
        $repoSitu = $manager->getRepository(Situation::class);
        $situation = $repoSitu->find($id);

        $production = new Production();
        $form = $this->createForm(ProductionType::class);
        $form->handleRequest($req);

        if($form->isSubmitted() && $form->isValid()){
            $doss = $user->getNom().$user->getPrenom().$user->getId().$user->getPromotion()->getNom().$user->getParcours()->getNom();
            $dossier = $this->getParameter('upload_directory').'\\'.$doss;
            if (!file_exists($dossier) && !is_dir($dossier)){
                mkdir($dossier,0777);
            }
            $file = $form->get('uri')->getData();
            $file_name = $file_uploader->upload($file,$doss);
            $production->setDesignation($form->get('designation')->getData());
            $production->setUri($file_name['nom']);
            $production->setUriEntier($file_name['nomEntier']);
            $production->setSituation($situation);
            $manager->persist($production);
            $manager->flush();

            $reponse = $this->redirectToRoute('afficherproduction', ['id' => $id]);
        }
        else {
            $reponse = $this->render('production/ajoutproduction.html.twig', [
                'form' => $form->createView(),
            ]);
        }

        return $reponse;
    }

    /**
     * @Route("/production/supprimerproduction/{id}{situationid}", name="supprimerproduction")
     */
    public function supprimerproduction(int $id,int $situationid): Response
    {
        $user = $this->getUser();
        $doctrine = $this->getDoctrine();
    	$manager = $doctrine->getManager();
    	$repoProd = $manager->getRepository(Production::class);
    	$production = $repoProd->find($id);
    	$uri = $production->getUriEntier();
    	
    	$dossier = $user->getNom().$user->getPrenom().$user->getId().$user->getPromotion()->getNom().$user->getParcours()->getNom();
    	$route = $this->getParameter('upload_directory').'/'.$dossier.'/'.$uri;
    	if (!file_exists($dossier)){
    	    unlink($route);
    	}
    	
        $manager->remove($production);
        $manager->flush();

        return $this->redirectToRoute('afficherproduction', ['id' => $situationid]);
    }

    /**
     * @Route("/production/modifierproduction/{id}{situationid}", name="modifierproduction")
     */
    public function modifierproduction(Request $req,int $id,int $situationid,FileUploader $file_uploader): Response
    {
        $user = $this->getUser();
        serialize($user);
    	$doctrine = $this->getDoctrine();
    	$manager = $doctrine->getManager();
    	$repoProd = $manager->getRepository(Production::class);
    	$production = $repoProd->find($id);
    	
    	$form = $this->createForm(ProductionType::class,$production);
    	$form->handleRequest($req);
    	
    	$dossier = $user->getNom().$user->getPrenom().$user->getId().$user->getPromotion()->getNom().$user->getParcours()->getNom();
    	$last_file = $production->getUriEntier();
    	
    	if($form->isSubmitted() && $form->isValid()){
    	    /*if($form->get('retour')->isClicked()){
    	        $reponse = $this->redirectToRoute('afficherproduction', ['id' => $situationid]);
    	    }
    	    else {*/
    	    $uri = $form->get('uri')->getData();
    	    $ancien_file = $this->getParameter('upload_directory').'/'.$dossier.'/'.$last_file;
    	    $file_uploader->supp($ancien_file);
    	    $file_name = $file_uploader->upload($uri,$dossier);
    	    $production->setUri($file_name['nom']);
    	    $production->setUriEntier($file_name['nomEntier']);
    	    $manager->persist($production);
    	    $manager->flush();
    	    $reponse = $this->redirectToRoute('afficherproduction', ['id' => $situationid]);
    	}
    	else {
    	    $reponse = $this->render('production/modifierproduction.html.twig', ['form' => $form->createView()]);
    	}
    	
    	return $reponse;
    }

    /**
     * @Route("/production/afficherproduction/{id}", name="afficherproduction")
     */
    public function afficherproduction(Request $req,int $id): Response
    {
        serialize($this->getUser());
        $doctrine = $this->getDoctrine();
        $manager = $doctrine->getManager();
        $repoSitu = $manager->getRepository(Situation::class);
        $situation = $repoSitu->find($id);
        $productions = $situation->getProductions();
        
        return $this->render('production/afficherproduction.html.twig', [
            'situation' => $situation,
            'productions' => $productions,
        ]);
    }
    
    /**
     * @Route("/production/telechargement/{nom}", name="telechargement")
     */
    public function telechargement(Request $req,string $nom): Response
    {
        $user = $this->getUser();
        serialize($user);
        $doss = $user->getNom().$user->getPrenom().$user->getId().$user->getPromotion()->getNom().$user->getParcours()->getNom();
        $file = $this->getParameter('upload_directory').'/'.$doss.'/'.$nom;
        return $this->file($file);
    }

    /**
     * @Route("/production/telechargement/{nom}{prenom}{id}{promotion}{parcours}/{uri}", name="telechargement_prof")
     */
    public function telechargementProf(Request $req,string $nom,string $prenom,string $id,string $uri,string $promotion,string $parcours): Response
    {
        $user = $this->getUser();
        serialize($user);
        $doss = $nom.$prenom.$id.$promotion.$parcours;
        $file = $this->getParameter('upload_directory').'/'.$doss.'/'.$uri;
        return $this->file($file);
    }
}

templates/production/afficherproduction.html.twig
{% extends 'base.html.twig' %}

{% block title %}Situations !{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<script type = "text/javascript">  

	function confirmSuppr() {
	
		if (confirm("Supprimer la Production ?") == false) {
	
			event.preventDefault();
	
		}
	}
</script>

<div class="example-wrapper">
<h1>Situations Titre: {{situation.libelle}}</h1><br/>
<br/>
{% if is_granted('ROLE_ETUD') %}
    <center><p><a href="{{ path('ajoutproduction', {'id':situation.id}) }}"><button id="btn" class="bx bx-plus-medical"></button></a><p></center>
    <br/>

    {% if productions is not empty %}
	    <table>
		    <tr><th>Libelle</th><th>Uri</th><th>Téléchargement<th>Modifier</th><th>Supprimer</th>

		    {% for p in productions %}
			    <tr><td>{{p.designation}}</td>
				<td>{{p.uri}}</td>
			    <td><a href="{{ path('telechargement', {'nom': p.uriEntier}) }}"><button class="btnUtil">Télécharger</button></a></td>
			    <td><a href="{{ path('modifierproduction', {'id': p.id, 'situationid': situation.id}) }}"><button class="btnUtil">Modifier</button></a></td>
			    <td><a href="{{ path('supprimerproduction', {'id': p.id, 'situationid': situation.id}) }}"><button class="btnUtil" onClick="confirmSuppr()">Supprimer</button></a></td>
		    {% endfor %}
	    </table>
    {% endif %}
    {% if productions is empty %}
    <center><h3>Vous n'avez pas de Productions</h3></center>
    {% endif %}
{% endif %}
{% if is_granted('ROLE_PROF') %}
    {% if productions is not empty %}
	    <table>
			<tr><th>Libelle</th><th>Uri</th><th>Télécharger</th></tr>

		    {% for p in productions %}
			    <tr><td>{{p.designation}}</td>
			    <td>{{p.uri}}</td>
				<td><a href="{{ path('telechargement_prof', {'nom': p.situation.etudiant.nom,'prenom':p.situation.etudiant.prenom,'id':p.situation.etudiant.id,'promotion':p.situation.etudiant.promotion.nom,'parcours':p.situation.etudiant.parcours.nom,'uri': p.uriEntier}) }}"><button class="btnUtil">Télécharger</button></a></td>
		    {% endfor %}
	    </table>
    {% endif %}
    {% if productions is empty %}
    <center><h3>Il n'y a pas de Production</h3></center>
    {% endif %}
{% endif %}
</div>
{% endblock %}

templates/production/ajoutproduction.html.twig
{% extends 'base.html.twig' %}

{% block title %}Situations !{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {{ form(form) }}
</div>
{% endblock %}

templates/production/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ProductionController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ '/LOCAL/home/boussariel/Projet_portefeuille/Projet/src/Controller/ProductionController.php'|file_link(0) }}">src/Controller/ProductionController.php</a></code></li>
        <li>Your template at <code><a href="{{ '/LOCAL/home/boussariel/Projet_portefeuille/Projet/templates/production/index.html.twig'|file_link(0) }}">templates/production/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/production/modifierproduction.html.twig
{% extends 'base.html.twig' %}

{% block title %}Situations !{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    {{ form(form) }}
</div>

{% endblock %}